name: Auto Data Collect

on:
  schedule:
    - cron: '13 17 * * 1-5' 
    - cron: '17 20 * * 1-5' 
    - cron: '43 20 * * 1-5' 
    - cron: '11 21 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # pytz 라이브러리 추가
        run: |
          pip install pandas yfinance pandas_market_calendars pytz

      - name: Run script
        # 실행 파일명 collect.py로 변경
        run: python collect.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add master_regular_close.csv
          git commit -m "Auto update: stock data" || echo "No changes to commit"
          git push
